[package]
name = "oc_physics"
version = "0.1.0"
edition = "2024"

[dependencies]
oc_utils = { path = "../oc_utils" }
oc_root = { path = "../oc_root" }

derive_more = { workspace = true, features = ["constructor"] }
rkyv.workspace = true
bresenham.workspace = true
