[package]
name = "oc_network"
version = "0.1.0"
edition = "2024"

[dependencies]
oc_individual = { path = "../oc_individual" }
oc_geo = { path = "../oc_geo" }
oc_world = { path = "../oc_world" }
rkyv.workspace = true
