[package]
name = "oc_individual"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
oc_root = { path = "../oc_root" }
oc_utils = { path = "../oc_utils" }
derive_more = { workspace = true, features = ["constructor"] }
rkyv.workspace = true
